CATEGORIES = [
    "Acoustics",
    "Aerodynamics",
    "Aeronautics",
    "Agroecology",
    "Agronomy",
    "Algebra",
    "Anatomy",
    "Andrology",
    "Angiology",
    "Animal_cognition",
    "Anthropology",
    "Applied mathematics",
    "Arachnology",
    "Archaeoastronomy",
    "Archaeological science",
    "Archaeology",
    "Architectural design",
    "Arithmetic",
    "Asteroseismology",
    "Astrobiology",
    "Astrodynamics",
    "Astrophysics",
    "Audiology",
    "Avionics",
    "Bacteriology",
    "Biochemistry",
    "Biogeochemistry",
    "Biogeography",
    "Biomechanics",
    "Biometrics",
    "Biophysics",
    "Botany",
    "Bryology",
    "Calligraphy",
    "Cardiology",
    "Cartography",
    "Cetology",
    "Chemistry",
    "Choreography",
    "Chorology",
    "Chronobiology",
    "Climatology",
    "Combinatorics",
    "Cosmology",
    "Demography",
    "Dermatology",
    "Dialectology",
    "Digital art",
    "Ecology",
    "Economics",
    "Electrodynamics",
    "Embryology",
    "Engineering",
    "Epigraphy",
    "Epistemology",
    "Ethnobiology",
    "Ethnology",
    "Ethnomusicology",
    "Eugenics",
    "Film theory",
    "Filmmaking",
    "Genetics",
    "Geobiology",
    "Geochemistry",
    "Geology",
    "Geomatics",
    "Geomicrobiology",
    "Geomorphology",
    "Geophysics",
    "Gerontology",
    "Glaciology",
    "Graphic design",
    "Hepatology",
    "Herpetology",
    "Histology",
    "Historiography",
    "Horology",
    "Horticulture",
    "Hydrodynamics",
    "Hydrogeology",
    "Hydrology",
    "Hydrostatics",
    "Ichnology",
    "Ichthyology",
    "Immunology",
    "Kinematics",
    "Landscape architecture",
    "Landscape history",
    "Laryngology",
    "Limnology",
    "Linguistics",
    "Macroeconomics",
    "Magnetohydrodynamics",
    "Malacology",
    "Mammalogy",
    "Mathematical analysis",
    "Mathematics",
    "Medicine",
    "Metallurgy",
    "Metaphysics",
    "Meteorology",
    "Methodology",
    "Metrology",
    "Microbiology",
    "Mineralogy",
    "Music education",
    "Music history",
    "Music theory",
    "Musical composition",
    "Mycology",
    "Nanotechnology",
    "Natural_sciences",
    "Nematology",
    "Neurology",
    "Number theory",
    "Numerology",
    "Oceanography",
    "Oenology",
    "Oncology",
    "Ontology",
    "Ophthalmology",
    "Optics",
    "Optometry",
    "Organology",
    "Ornithology",
    "Orthodontics",
    "Osteology",
    "Otology",
    "Paleobotany",
    "Paleoclimatology",
    "Paleoecology",
    "Paleontology",
    "Palynology",
    "Parapsychology",
    "Pathology",
    "Pedagogy",
    "Pedology",
    "Petrology",
    "Pharmacognosy",
    "Pharmacology",
    "Philology",
    "Philosophy_of_mathematics",
    "Phonetics",
    "Photography",
    "Physics",
    "Physiology",
    "Plant_ecology",
    "Plant_genetics",
    "Pneumography",
    "Podiatry",
    "Primatology",
    "Prosthetics",
    "Psephology",
    "Psychiatry",
    "Psychogeriatrics",
    "Psycholinguistics",
    "Psychology",
    "Psychometrics",
    "Psychopathology",
    "Public law",
    "Puppetry",
    "Radiochemistry",
    "Radiology",
    "Rheology",
    "Rhetoric",
    "Robotics",
    "Sculpture",
    "Seismology",
    "Semantics",
    "Sericulture",
    "Sexology",
    "Socioeconomics",
    "Sociolinguistics",
    "Sociology",
    "Speleology",
    "Statistics",
    "Stratigraphy",
    "Taphonomy",
    "Technical drawing",
    "Telematics",
    "Teleology",
    "Thanatology",
    "Theology",
    "Thermodynamics",
    "Topology",
    "Toxicology",
    "Urban planning",
    "Urology",
    "Ventriloquism",
    "Virology",
    "Zoology",
]

SEED = 42
